services:
  web-profile:
    image: web-profile:latest
    build: .
    container_name: web-profile
    restart: always
    ports:
      - "2001:80"
    networks:
      - web-profile-net

networks:
  web-profile-net:
    driver: bridge
