services:
  web-profile-dev:
    image: web-profile-dev:latest
    build: .
    container_name: web-profile-dev
    restart: always
    ports:
      - "2001:80"
    networks:
      - web-profile-net

networks:
  web-profile-net:
    driver: bridge
